name: Build
description: Build nginx image
inputs:
  version:
    description: version
    required: true
  user_id:
    description: user id
    required: false
  group_id:
    description: group id
    required: false
  tags:
    description: image tags
    required: true
  platform:
    description: docker platform
    required: false
    default: linux/amd64
runs:
  using: "composite"
  steps:
  - name: Build and push image to docker.io
    env:
      NGINX_VER: ${{ inputs.version }}
      SUPER_USER_ID: ${{ inputs.user_id }}
      SUPER_GROUP_ID: ${{ inputs.group_id }}
      TAGS: ${{ inputs.tags }}
      PLATFORM: ${{ inputs.platform }}
      DOCKER_REGISTRY: docker.io
    run: |
      set -e
      make buildx-build-amd64
      make test
      make buildx-build
      . $GITHUB_ACTION_PATH/release.sh
    shell: bash
  - name: Build and push amd64 image to registry
    env:
      NGINX_VER: ${{ inputs.version }}
      TAGS: ${{ inputs.tags }}
      PLATFORM: linux/amd64
    run: |
      set -e
      DOCKER_USERNAME="${DOCKER_USERNAME}" DOCKER_PASSWORD="${DOCKER_PASSWORD}" . $GITHUB_ACTION_PATH/release.sh
    shell: bash
